# Generated by Django 4.0.6 on 2022-08-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#0000FF', 'Синий'), ('#00ff00', 'Зелёный'), ('#FF0000', 'Красный'), ('#ffffff', 'Белый')], max_length=7, unique=True, verbose_name='Цвет тега'),
        ),
    ]
